name: pressy_client
description: Pressy Client Mobile App.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.3

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  bloc: ^0.9.5
  flutter_bloc: ^0.6.3
  equatable: ^0.2.3
  json_serializable: ^2.0.3
  http: ^0.12.0
  shared_preferences: ^0.5.1+1
  flutter_simple_dependency_injection: ^1.0.1
  flutter_slidable: ^0.4.9
  flutter_google_places: ^0.2.0
  uuid: ^2.0.0
  location: ^1.4.1
  intl: any
  flutter_staggered_grid_view: ^0.2.7
  dio: ^2.1.3

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/mocks/v1/auth/post.json
    - assets/mocks/v1/auth/refresh/post.json
    - assets/mocks/v1/member/get.json
    - assets/mocks/v1/member/post.json

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Avenir
      fonts:
        - asset: fonts/Avenir-Book.ttf
          weight: 300
        - asset: fonts/Avenir-Medium.ttf
          weight: 400
        - asset: fonts/Avenir-Heavy.ttf
          weight: 600
        - asset: fonts/Avenir-Black.ttf
          weight: 700